// Icon manifest for the Forma System Icon Set downloader.
//
// HOW TO ADD MORE ICONS
// ----------------------
// Each entry in CATEGORIES needs a `slug` matching a folder under /icons,
// and each icon needs an svg file at:
//   icons/<category-slug>/<weight>/<icon-slug>.svg
// normalized to a 24x24 viewBox with `fill="var(--fill-0, #424242)"` on
// its paths (see icons/alerts-feedback/light/*.svg for the pattern).
// Once files exist on disk, add the icon slug to that category's `icons`
// array below (or generate this file from a folder listing — see README).

const WEIGHTS = ["light", "medium", "bold", "filled"];

const CATEGORIES = [
  { slug: "alerts-feedback", name: "Alerts & Feedback" },
  { slug: "arrows", name: "Arrows" },
  { slug: "charts", name: "Charts" },
  { slug: "communication", name: "Communications" },
  { slug: "developments", name: "Developments" },
  { slug: "editor", name: "Editor" },
  { slug: "education", name: "Education" },
  { slug: "files", name: "Files" },
  { slug: "finance-ecommerce", name: "Finance & eCommerce" },
  { slug: "general", name: "General" },
  { slug: "layouts", name: "Layouts" },
  { slug: "maps-travel", name: "Maps & Travel" },
  { slug: "media-devices", name: "Media & Devices" },
  { slug: "security", name: "Security" },
  { slug: "shapes", name: "Shapes" },
  { slug: "sports", name: "Sports" },
  { slug: "time", name: "Time" },
  { slug: "users", name: "Users" },
  { slug: "weather", name: "Weather" },
];

// icons[category-slug] = { [weight]: [iconSlug, ...] }
const ICONS = {
  "alerts-feedback": {
    light: ["alert-01", "alert-02", "alert-03", "alert-04", "announcement", "bell-notification-01", "bell-notification-02", "bell-notification-off", "bell-notification-ringing", "box-message", "do-not-disturb", "fire", "help-question", "info-01", "info-02", "info-03", "info-04", "label-important", "notification-message", "thumbs-down", "thumbs-up"],
    medium: ["alert-01", "alert-02", "alert-03", "alert-04", "announcement", "bell-notification-01", "bell-notification-02", "bell-notification-off", "bell-notification-ringing", "box-message", "do-not-disturb", "fire", "help-question", "info-01", "info-02", "info-03", "info-04", "label-important", "notification-message", "thumbs-down", "thumbs-up"],
    bold: ["alert-01", "alert-02", "alert-03", "alert-04", "announcement", "bell-notification-01", "bell-notification-02", "bell-notification-off", "bell-notification-ringing", "box-message", "do-not-disturb", "fire", "help-question", "info-01", "info-02", "info-03", "info-04", "label-important", "notification-message", "thumbs-down", "thumbs-up"],
    filled: ["alert-01", "alert-02", "alert-03", "alert-04", "announcement", "bell-notification-01", "bell-notification-02", "bell-notification-off", "bell-notification-ringing", "box-message", "do-not-disturb", "fire", "help-question", "info-01", "info-02", "info-03", "info-04", "label-important", "notification-message", "thumbs-down", "thumbs-up"],
  },
  "arrows": {
    light: ["arrow-down-circle", "arrow-down-left-circle", "arrow-down-left-square", "arrow-down-left", "arrow-down-right-circle", "arrow-down-right-square", "arrow-down-right", "arrow-down-square", "arrow-down", "arrow-left-circle", "arrow-left-square", "arrow-left", "arrow-right-circle", "arrow-right-square", "arrow-right", "arrow-split-down", "arrow-split-left", "arrow-split-right", "arrow-split-up", "arrow-up-circle", "arrow-up-left-circle", "arrow-up-left-square", "arrow-up-right-circle", "arrow-up-right-square", "arrow-up-square", "arrow-up", "chevron-down-circle", "chevron-down-small", "chevron-down-square", "chevron-down", "chevron-left-circle", "chevron-left-small", "chevron-left-square", "chevron-left", "chevron-right-circle", "chevron-right-small", "chevron-right-square", "chevron-right", "chevron-up-circle", "chevron-up-small", "chevron-up-square", "chevron-up", "curved-arrows-left-right", "curved-arrows-up-down", "double-arrow-down", "double-arrow-left", "double-arrow-right", "double-arrow-up", "infinity", "next", "previous", "refresh-left", "refresh-right", "reverse-left", "reverse-right", "shuffle", "subdirectory-down-alt", "subdirectory-down", "subdirectory-left-alt", "subdirectory-left", "subdirectory-right-alt", "subdirectory-right", "subdirectory-up-alt", "subdirectory-up", "switch-horizontal", "switch-vertical", "undo-left", "undo-right", "unfold-less-horizontal", "unfold-less-vertical", "unfold-more-horizontal", "unfold-more-vertical"],
    medium: ["arrow-down-circle", "arrow-down-left-circle", "arrow-down-left-square", "arrow-down-left", "arrow-down-right-circle", "arrow-down-right-square", "arrow-down-right", "arrow-down-square", "arrow-down", "arrow-left-circle", "arrow-left-square", "arrow-left", "arrow-right-circle", "arrow-right-square", "arrow-right", "arrow-split-down", "arrow-split-left", "arrow-split-right", "arrow-split-up", "arrow-up-circle", "arrow-up-left-circle", "arrow-up-left-square", "arrow-up-right-circle", "arrow-up-right-square", "arrow-up-square", "arrow-up", "chevron-down-circle", "chevron-down-small", "chevron-down-square", "chevron-down", "chevron-left-circle", "chevron-left-small", "chevron-left-square", "chevron-left", "chevron-right-circle", "chevron-right-small", "chevron-right-square", "chevron-right", "chevron-up-circle", "chevron-up-small", "chevron-up-square", "chevron-up", "curved-arrows-left-right", "curved-arrows-up-down", "double-arrow-down", "double-arrow-left", "double-arrow-right", "double-arrow-up", "infinity", "next", "previous", "refresh-left", "refresh-right", "reverse-left", "reverse-right", "shuffle", "subdirectory-down-alt", "subdirectory-down", "subdirectory-left-alt", "subdirectory-left", "subdirectory-right-alt", "subdirectory-right", "subdirectory-up-alt", "subdirectory-up", "switch-horizontal", "switch-vertical", "undo-left", "undo-right", "unfold-less-horizontal", "unfold-less-vertical", "unfold-more-horizontal", "unfold-more-vertical"],
    bold: ["arrow-down-circle", "arrow-down-left-circle", "arrow-down-left-square", "arrow-down-left", "arrow-down-right-circle", "arrow-down-right-square", "arrow-down-right", "arrow-down-square", "arrow-down", "arrow-left-circle", "arrow-left-square", "arrow-left", "arrow-right-circle", "arrow-right-square", "arrow-right", "arrow-split-down", "arrow-split-left", "arrow-split-right", "arrow-split-up", "arrow-up-circle", "arrow-up-left-circle", "arrow-up-left-square", "arrow-up-right-circle", "arrow-up-right-square", "arrow-up-square", "arrow-up", "chevron-down-circle", "chevron-down-small", "chevron-down-square", "chevron-down", "chevron-left-circle", "chevron-left-small", "chevron-left-square", "chevron-left", "chevron-right-circle", "chevron-right-small", "chevron-right-square", "chevron-right", "chevron-up-circle", "chevron-up-small", "chevron-up-square", "chevron-up", "curved-arrows-left-right", "curved-arrows-up-down", "double-arrow-down", "double-arrow-left", "double-arrow-right", "double-arrow-up", "infinity", "next", "previous", "refresh-left", "refresh-right", "reverse-left", "reverse-right", "shuffle", "subdirectory-down-alt", "subdirectory-down", "subdirectory-left-alt", "subdirectory-left", "subdirectory-right-alt", "subdirectory-right", "subdirectory-up-alt", "subdirectory-up", "switch-horizontal", "switch-vertical", "undo-left", "undo-right", "unfold-less-horizontal", "unfold-less-vertical", "unfold-more-horizontal", "unfold-more-vertical"],
    filled: ["arrow-down-circle", "arrow-down-left-circle", "arrow-down-left-square", "arrow-down-left", "arrow-down-right-circle", "arrow-down-right-square", "arrow-down-right", "arrow-down-square", "arrow-down", "arrow-left-circle", "arrow-left-square", "arrow-left", "arrow-right-circle", "arrow-right-square", "arrow-right", "arrow-split-down", "arrow-split-left", "arrow-split-right", "arrow-split-up", "arrow-up-circle", "arrow-up-left-circle", "arrow-up-left-square", "arrow-up-right-circle", "arrow-up-right-square", "arrow-up-square", "arrow-up", "chevron-down-circle", "chevron-down-small", "chevron-down-square", "chevron-down", "chevron-left-circle", "chevron-left-small", "chevron-left-square", "chevron-left", "chevron-right-circle", "chevron-right-small", "chevron-right-square", "chevron-right", "chevron-up-circle", "chevron-up-small", "chevron-up-square", "chevron-up", "curved-arrows-left-right", "curved-arrows-up-down", "double-arrow-down", "double-arrow-left", "double-arrow-right", "double-arrow-up", "infinity", "next", "previous", "refresh-left", "refresh-right", "reverse-left", "reverse-right", "shuffle", "subdirectory-down-alt", "subdirectory-down", "subdirectory-left-alt", "subdirectory-left", "subdirectory-right-alt", "subdirectory-right", "subdirectory-up-alt", "subdirectory-up", "switch-horizontal", "switch-vertical", "undo-left", "undo-right", "unfold-less-horizontal", "unfold-less-vertical", "unfold-more-horizontal", "unfold-more-vertical"],
  },
  "charts": {
    light: ["add-bars-square", "bars-01", "bars-02", "bars-03", "bars-04", "bars-05", "bars-06", "bars-horizontal-01", "bars-horizontal-02", "bars-horizontal-03", "bars-horizontal-04", "bars-horizontal-05", "bars-horizontal-06", "bars-square", "line-chart-down-01", "line-chart-down-02", "line-chart-down-square", "line-chart-up-01", "line-chart-up-02", "line-chart-up-square", "pie-chart-01", "pie-chart-02", "presentation", "remove-bars-square", "scoreboard"],
    medium: ["add-bars-square", "bars-01", "bars-02", "bars-03", "bars-04", "bars-05", "bars-06", "bars-horizontal-01", "bars-horizontal-02", "bars-horizontal-03", "bars-horizontal-04", "bars-horizontal-05", "bars-horizontal-06", "bars-square", "line-chart-down-01", "line-chart-down-02", "line-chart-down-square", "line-chart-up-01", "line-chart-up-02", "line-chart-up-square", "pie-chart-01", "pie-chart-02", "presentation", "remove-bars-square", "scoreboard"],
    bold: ["add-bars-square", "bars-01", "bars-02", "bars-03", "bars-04", "bars-05", "bars-06", "bars-horizontal-01", "bars-horizontal-02", "bars-horizontal-03", "bars-horizontal-04", "bars-horizontal-05", "bars-horizontal-06", "bars-square", "line-chart-down-01", "line-chart-down-02", "line-chart-down-square", "line-chart-up-01", "line-chart-up-02", "line-chart-up-square", "pie-chart-01", "pie-chart-02", "presentation", "remove-bars-square", "scoreboard"],
    filled: ["add-bars-square", "bars-01", "bars-02", "bars-03", "bars-04", "bars-05", "bars-06", "bars-horizontal-01", "bars-horizontal-02", "bars-horizontal-03", "bars-horizontal-04", "bars-horizontal-05", "bars-horizontal-06", "bars-square", "line-chart-down-01", "line-chart-down-02", "line-chart-down-square", "line-chart-up-01", "line-chart-up-02", "line-chart-up-square", "pie-chart-01", "pie-chart-02", "presentation", "remove-bars-square", "scoreboard"],
  },
  "communication": {
    light: ["add-phone", "annotation-alert", "annotation-check", "annotation-dots", "annotation-heart", "annotation-info", "annotation-plus", "annotation-question", "annotation-x", "annotation", "chat-01", "chat-02", "chat-03", "chat-check", "chat-dots", "chat-heart", "chat-notification", "chat-plus", "chat-x", "email-01", "email-02", "inbox", "inboxes", "news-paper", "phone-call", "phone-hung-up", "phone-incoming", "phone-outgoing", "phone-pause", "phone-x", "phone", "send-01", "send-02"],
    medium: ["add-phone", "annotation-alert", "annotation-check", "annotation-dots", "annotation-heart", "annotation-info", "annotation-plus", "annotation-question", "annotation-x", "annotation", "chat-01", "chat-02", "chat-03", "chat-check", "chat-dots", "chat-heart", "chat-notification", "chat-plus", "chat-x", "email-01", "email-02", "inbox", "inboxes", "news-paper", "phone-call", "phone-hung-up", "phone-incoming", "phone-outgoing", "phone-pause", "phone-x", "phone", "send-01", "send-02"],
    bold: ["add-phone", "annotation-alert", "annotation-check", "annotation-dots", "annotation-heart", "annotation-info", "annotation-plus", "annotation-question", "annotation-x", "annotation", "chat-01", "chat-02", "chat-03", "chat-check", "chat-dots", "chat-heart", "chat-notification", "chat-plus", "chat-x", "email-01", "email-02", "inbox", "inboxes", "news-paper", "phone-call", "phone-hung-up", "phone-incoming", "phone-outgoing", "phone-pause", "phone-x", "phone", "send-01", "send-02"],
    filled: ["add-phone", "annotation-check", "annotation-dots", "annotation-heart", "annotation-info", "annotation-plus", "annotation-question", "annotation-x", "annotation", "chat-01", "chat-02", "chat-03", "chat-check", "chat-dots", "chat-heart", "chat-notification", "chat-plus", "chat-x", "email-01", "email-02", "inbox", "inboxes", "news-paper", "phone-call", "phone-hung-up", "phone-incoming", "phone-outgoing", "phone-pause", "phone-x", "phone", "send-01", "send-02"],
  },
  "developments": {
    light: ["architecture", "bot", "brackets-check", "brackets-ellipses", "brackets-minus", "brackets-plus", "brackets-slash", "brackets-x", "brackets", "brick", "browser", "bug", "code-browser", "code-snippet-01", "code-snippet-02", "code-snippet-circle-01", "code-snippet-circle-02", "code-snippet-square-01", "code-snippet-square-02", "construction", "cpu-chip-01", "cpu-chip-02", "database-01", "database-03", "dataflow-01", "dataflow-02", "dataflow-03", "dataflow-04", "factory-workshop", "file-code", "folder-code", "jigsaw", "modular", "package-check", "package-minus", "package-plus", "package-search", "package-x", "package", "puzzle-piece-01", "puzzle-piece-02", "qr-code", "reuse", "slash", "terminal-browser", "terminal", "variable"],
    medium: ["architecture", "bot", "brackets-check", "brackets-ellipses", "brackets-minus", "brackets-plus", "brackets-slash", "brackets-x", "brackets", "brick", "browser", "bug", "code-browser", "code-snippet-01", "code-snippet-02", "code-snippet-circle-01", "code-snippet-circle-02", "code-snippet-square-01", "code-snippet-square-02", "construction", "cpu-chip-01", "cpu-chip-02", "database-01", "database-03", "dataflow-01", "dataflow-02", "dataflow-03", "dataflow-04", "factory-workshop", "file-code", "folder-code", "jigsaw", "modular", "package-check", "package-minus", "package-plus", "package-search", "package-x", "package", "puzzle-piece-01", "puzzle-piece-02", "qr-code", "reuse", "slash", "terminal-browser", "terminal", "variable"],
    bold: ["architecture", "bot", "brackets-check", "brackets-ellipses", "brackets-minus", "brackets-plus", "brackets-slash", "brackets-x", "brackets", "brick", "browser", "bug", "code-browser", "code-snippet-01", "code-snippet-02", "code-snippet-circle-01", "code-snippet-circle-02", "code-snippet-square-01", "code-snippet-square-02", "construction", "cpu-chip-01", "cpu-chip-02", "database-01", "database-03", "dataflow-01", "dataflow-02", "dataflow-03", "dataflow-04", "factory-workshop", "file-code", "folder-code", "jigsaw", "modular", "package-check", "package-minus", "package-plus", "package-search", "package-x", "package", "puzzle-piece-01", "puzzle-piece-02", "qr-code", "reuse", "slash", "terminal-browser", "terminal", "variable"],
    filled: ["architecture", "bot", "brackets-check", "brackets-ellipses", "brackets-minus", "brackets-plus", "brackets-slash", "brackets-x", "brackets", "brick", "browser", "bug", "code-browser", "code-snippet-01", "code-snippet-02", "code-snippet-circle-01", "code-snippet-circle-02", "code-snippet-square-01", "code-snippet-square-02", "construction", "cpu-chip-01", "cpu-chip-02", "database-01", "database-03", "dataflow-01", "dataflow-02", "dataflow-03", "dataflow-04", "factory-workshop", "file-code", "folder-code", "jigsaw", "modular", "package-check", "package-minus", "package-plus", "package-search", "package-x", "package", "puzzle-piece-01", "puzzle-piece-02", "qr-code", "reuse", "slash", "terminal-browser", "terminal", "variable"],
  },
  "editor": {
    light: ["align-center", "align-justify-forced", "align-justify", "align-left", "align-right", "angle", "bazier", "bold", "brush-01", "brush-02", "brush-03", "bullet-points-01", "bullet-points-02", "camera", "colours", "command", "contrast", "copy", "crop", "cursor-01", "cursor-02", "cursor-box", "cursor-click-01", "cursor-click-02", "delete", "design-services", "drop", "dropper", "edit-01", "edit-02", "eraser", "feather", "hand", "heading", "image", "images", "indent-left-01", "indent-left-02", "indent-right-01", "indent-right-02", "italic", "label-off", "label", "letter-spacing", "line-height", "magic-wand-01", "magic-wand-02", "move", "new-label", "paint", "palette", "pen-tool-01", "pen-tool-add", "pencil", "perspective-01", "perspective-02", "reflect-01", "reflect-02", "roller-paint", "scale", "scissor", "skew", "strikethrough", "style", "text-input", "transform", "type", "underline", "zoom-in", "zoom-out"],
    medium: ["align-center", "align-justify-forced", "align-justify", "align-left", "align-right", "angle", "bazier", "bold", "brush-01", "brush-02", "brush-03", "bullet-points-01", "bullet-points-02", "camera", "colours", "command", "contrast", "copy", "crop", "cursor-01", "cursor-02", "cursor-box", "cursor-click-01", "cursor-click-02", "delete", "design-services", "drop", "dropper", "edit-01", "edit-02", "eraser", "feather", "hand", "heading", "image", "images", "indent-left-01", "indent-left-02", "indent-right-01", "indent-right-02", "italic", "label-off", "label", "letter-spacing", "line-height", "magic-wand-01", "magic-wand-02", "move", "new-label", "paint", "palette", "pen-tool-01", "pen-tool-add", "pencil", "perspective-01", "perspective-02", "reflect-01", "reflect-02", "roller-paint", "scale", "scissor", "skew", "strikethrough", "style", "text-input", "transform", "type", "underline", "zoom-in", "zoom-out"],
    bold: ["align-center", "align-justify-forced", "align-justify", "align-left", "align-right", "angle", "bazier", "bold", "brush-01", "brush-02", "brush-03", "bullet-points-01", "bullet-points-02", "camera", "colours", "command", "contrast", "copy", "crop", "cursor-01", "cursor-02", "cursor-box", "cursor-click-01", "cursor-click-02", "delete", "design-services", "drop", "dropper", "edit-01", "edit-02", "eraser", "feather", "hand", "heading", "image", "images", "indent-left-01", "indent-left-02", "indent-right-01", "indent-right-02", "italic", "label-off", "label", "letter-spacing", "line-height", "magic-wand-01", "magic-wand-02", "move", "new-label", "paint", "palette", "pen-tool-01", "pen-tool-add", "pencil", "perspective-01", "perspective-02", "reflect-01", "reflect-02", "roller-paint", "scale", "scissor", "skew", "strikethrough", "style", "text-input", "transform", "type", "underline", "zoom-in", "zoom-out"],
    filled: ["align-center", "align-justify-forced", "align-justify", "align-left", "align-right", "angle", "bazier", "bold", "brush-01", "brush-02", "brush-03", "bullet-points-01", "bullet-points-02", "camera", "colours", "command", "contrast", "copy", "crop", "cursor-01", "cursor-02", "cursor-box", "cursor-click-01", "cursor-click-02", "delete", "design-services", "drop", "dropper", "edit-01", "edit-02", "eraser", "feather", "hand", "heading", "image", "images", "indent-left-01", "indent-left-02", "indent-right-01", "indent-right-02", "italic", "label-off", "label", "letter-spacing", "line-height", "magic-wand-01", "magic-wand-02", "move", "new-label", "paint", "palette", "pen-tool-01", "pen-tool-add", "pencil", "perspective-01", "perspective-02", "reflect-01", "reflect-02", "roller-paint", "scale", "scissor", "skew", "strikethrough", "style", "text-input", "transform", "type", "underline", "zoom-in", "zoom-out"],
  },
  "education": {
    light: ["atom", "award-01", "award-02", "backpack", "beaker", "book-01", "book-02", "briefcase-01", "calculator", "certificate", "compass-tool", "glasses-01", "glasses-02", "graduation-cap", "medal", "microscope", "molecule", "organism", "ruler", "stand", "telescope", "trophy-01", "trophy-02"],
    medium: ["atom", "award-01", "award-02", "backpack", "beaker", "book-01", "book-02", "briefcase-01", "calculator", "certificate", "compass-tool", "glasses-01", "glasses-02", "graduation-cap", "medal", "microscope", "molecule", "organism", "ruler", "stand", "telescope", "trophy-01", "trophy-02"],
    bold: ["atom", "award-01", "award-02", "backpack", "beaker", "book-01", "book-02", "briefcase-01", "calculator", "certificate", "compass-tool", "glasses-01", "glasses-02", "graduation-cap", "medal", "microscope", "molecule", "organism", "ruler", "stand", "telescope", "trophy-01", "trophy-02"],
    filled: ["atom", "award-01", "award-02", "backpack", "beaker", "book-01", "book-02", "briefcase-01", "calculator", "certificate", "compass-tool", "glasses-01", "glasses-02", "graduation-cap", "medal", "microscope", "molecule", "organism", "ruler", "stand", "telescope", "trophy-01", "trophy-02"],
  },
  "files": {
    light: ["attachment-01", "attachment-02", "box", "clipboard-attachment", "clipboard-check", "clipboard-download", "clipboard-minus", "clipboard-plus", "clipboard-search", "clipboard-x", "clipboard", "file-01", "file-02", "file-03", "file-attachment-01", "file-attachment-02", "file-attachment-03", "file-check-01", "file-check-02", "file-check-03", "file-download-01", "file-download-02", "file-download-03", "file-favorite-01", "file-favorite-02", "file-favorite-03", "file-lock-01", "file-lock-03", "file-minus-01", "file-minus-02", "file-minus-03", "file-plus-01", "file-plus-02", "file-plus-03", "file-question-01", "file-question-02", "file-question-03", "file-search-01", "file-search-02", "file-search-03", "file-unlock-01", "file-unlock-02", "file-unlock-03", "file-x-01", "file-x-02", "file-x-03", "files-pages", "folder-check", "folder-download", "folder-favorite", "folder-lock", "folder-minus", "folder-plus", "folder-question", "folder-search", "folder-unlock", "folder-x", "folder", "library-add", "library-books", "library-check", "library-music", "library-photo", "library-video", "sticker-01", "sticker-02"],
    medium: ["attachment-01", "attachment-02", "box", "clipboard-attachment", "clipboard-check", "clipboard-download", "clipboard-minus", "clipboard-plus", "clipboard-search", "clipboard-x", "clipboard", "file-01", "file-02", "file-03", "file-attachment-01", "file-attachment-02", "file-attachment-03", "file-check-01", "file-check-02", "file-check-03", "file-download-01", "file-download-02", "file-download-03", "file-favorite-01", "file-favorite-02", "file-favorite-03", "file-lock-01", "file-lock-03", "file-minus-01", "file-minus-02", "file-minus-03", "file-plus-01", "file-plus-02", "file-plus-03", "file-question-01", "file-question-02", "file-question-03", "file-search-01", "file-search-02", "file-search-03", "file-unlock-01", "file-unlock-02", "file-unlock-03", "file-x-01", "file-x-02", "file-x-03", "files-pages", "folder-check", "folder-download", "folder-favorite", "folder-lock", "folder-minus", "folder-plus", "folder-question", "folder-search", "folder-unlock", "folder-x", "folder", "library-add", "library-books", "library-check", "library-music", "library-photo", "library-video", "sticker-01", "sticker-02"],
    bold: ["attachment-01", "attachment-02", "box", "clipboard-attachment", "clipboard-check", "clipboard-download", "clipboard-minus", "clipboard-plus", "clipboard-search", "clipboard-x", "clipboard", "file-01", "file-02", "file-03", "file-attachment-01", "file-attachment-02", "file-attachment-03", "file-check-01", "file-check-02", "file-check-03", "file-download-01", "file-download-02", "file-download-03", "file-favorite-01", "file-favorite-02", "file-favorite-03", "file-lock-01", "file-lock-03", "file-minus-01", "file-minus-02", "file-minus-03", "file-plus-01", "file-plus-02", "file-plus-03", "file-question-01", "file-question-02", "file-question-03", "file-search-01", "file-search-02", "file-search-03", "file-unlock-01", "file-unlock-02", "file-unlock-03", "file-x-01", "file-x-02", "file-x-03", "files-pages", "folder-check", "folder-download", "folder-favorite", "folder-lock", "folder-minus", "folder-plus", "folder-question", "folder-search", "folder-unlock", "folder-x", "folder", "library-add", "library-books", "library-check", "library-music", "library-photo", "library-video", "sticker-01", "sticker-02"],
    filled: ["attachment-01", "attachment-02", "box", "clipboard-attachment", "clipboard-check", "clipboard-download", "clipboard-minus", "clipboard-plus", "clipboard-search", "clipboard-x", "clipboard", "file-01", "file-02", "file-03", "file-attachment-01", "file-attachment-02", "file-attachment-03", "file-check-01", "file-check-02", "file-check-03", "file-download-01", "file-download-02", "file-download-03", "file-favorite-01", "file-favorite-02", "file-favorite-03", "file-lock-01", "file-lock-03", "file-minus-01", "file-minus-02", "file-minus-03", "file-plus-01", "file-plus-02", "file-plus-03", "file-question-01", "file-question-02", "file-question-03", "file-search-01", "file-search-02", "file-search-03", "file-unlock-01", "file-unlock-02", "file-unlock-03", "file-x-01", "file-x-02", "file-x-03", "files-pages", "folder-check", "folder-download", "folder-favorite", "folder-lock", "folder-minus", "folder-plus", "folder-question", "folder-search", "folder-unlock", "folder-x", "folder", "library-add", "library-books", "library-check", "library-music", "library-photo", "library-video", "sticker-01", "sticker-02"],
  },
  "finance-ecommerce": {
    light: ["bank", "card-down", "card-edit", "card-lock", "card-membership", "card-minus", "card-plus", "card-up", "card-x", "card", "cart-empty", "diamond", "insurance", "pan-card", "receipt-check", "receipt", "redeem", "safe", "sale-01", "sale-02", "sale-03", "sale-04", "shopping-bag-01", "shopping-bag-02", "shopping-bag-03", "shopping-basket", "stocks", "tag", "trend", "wallet-01", "wallet-02", "wallet-03", "wallet-04"],
    medium: ["bank", "card-down", "card-edit", "card-lock", "card-membership", "card-minus", "card-plus", "card-up", "card-x", "card", "cart-empty", "diamond", "insurance", "pan-card", "receipt-check", "receipt", "redeem", "safe", "sale-01", "sale-02", "sale-03", "sale-04", "shopping-bag-01", "shopping-bag-02", "shopping-bag-03", "shopping-basket", "stocks", "tag", "trend", "wallet-01", "wallet-02", "wallet-03", "wallet-04"],
    bold: ["bank", "card-down", "card-edit", "card-lock", "card-membership", "card-minus", "card-plus", "card-up", "card-x", "card", "cart-empty", "diamond", "insurance", "pan-card", "receipt-check", "receipt", "redeem", "safe", "sale-01", "sale-02", "sale-03", "sale-04", "shopping-bag-01", "shopping-bag-02", "shopping-bag-03", "shopping-basket", "stocks", "tag", "trend", "wallet-01", "wallet-02", "wallet-03", "wallet-04"],
    filled: ["bank", "card-down", "card-edit", "card-lock", "card-membership", "card-minus", "card-plus", "card-up", "card-x", "card", "cart-empty", "diamond", "insurance", "pan-card", "receipt-check", "receipt", "redeem", "safe", "sale-01", "sale-02", "sale-03", "sale-04", "shopping-bag-01", "shopping-bag-02", "shopping-bag-03", "shopping-basket", "stocks", "tag", "trend", "wallet-01", "wallet-02", "wallet-03", "wallet-04"],
  },
  "general": {
    light: ["123", "3d-rotation", "abc", "accessibility", "accessible", "activity", "add-bookmark", "add-home", "anchor", "archive", "asterisk", "at-sign", "bone-pet-supplies", "bookmark-added", "bookmark", "bookmarks", "celebration", "check-tik-circle", "check-tik-square", "check-tik", "check-verified", "checkbox-checked", "checkbox-empty", "checkbox-indeterminate", "checklist", "chicken", "cleaning-services", "close-cancel-circle", "close-cancel-square", "close-cancel", "cloud-download", "cloud-upload", "coconut-tree", "cruelty-free-bunny", "dashboard", "delete", "dentistry", "divide", "doctor", "download", "eco-leaf", "egg", "electrical-services", "equal-not", "equal", "eye-closed", "eye-open", "fan-off", "fashion-clothes", "filter-01", "filter-02", "fish", "flower-01", "flower-02", "gesture", "grid-menu", "hash-01", "hash-02", "healing", "heart-activity", "heart-broken", "heart", "hearts", "hive", "home", "ladder", "lamp", "link-01", "link-02", "link-broken-01", "link-broken-02", "loading", "medical-square-hospital", "medical", "menu-left", "menu-more-horzontal", "menu-more-vertical", "menu-right", "menu", "minus-circle", "minus-square", "minus", "mop", "office", "pharmacy-medical-pill", "pin-01", "pin-02", "pine-tree", "plant", "plus-circle", "plus-square", "plus", "power-plug-off", "power-plug", "projects-apps", "radio-empty", "remove-bookmark", "rocking-chair", "save", "search", "settings-01", "settings-02", "settings-03", "share-01", "share-02", "share-03", "share-04", "sign-in-log-in", "sign-out-log-out", "skull", "speedometer", "target-01", "target-02", "target-03", "tool", "toys-fan", "translate", "tree", "upload", "vaccine", "veg-non-veg", "virus", "wall"],
    medium: ["123", "3d-rotation", "abc", "accessibility", "accessible", "activity", "add-bookmark", "add-home", "anchor", "archive", "asterisk", "at-sign", "bone-pet-supplies", "bookmark-added", "bookmark", "bookmarks", "celebration", "check-tik-circle", "check-tik-square", "check-tik", "check-verified", "checkbox-checked", "checkbox-empty", "checkbox-indeterminate", "checklist", "chicken", "cleaning-services", "close-cancel-circle", "close-cancel-square", "close-cancel", "cloud-download", "cloud-upload", "coconut-tree", "cruelty-free-bunny", "dashboard", "delete", "dentistry", "divide", "doctor", "download", "eco-leaf", "egg", "electrical-services", "equal-not", "equal", "eye-closed", "eye-open", "fan-off", "fashion-clothes", "filter-01", "filter-02", "fish", "flower-01", "flower-02", "gesture", "grid-menu", "hash-01", "hash-02", "healing", "heart-activity", "heart-broken", "heart", "hearts", "hive", "home", "ladder", "lamp", "link-01", "link-02", "link-broken-01", "link-broken-02", "loading", "medical-square-hospital", "medical", "menu-left", "menu-more-horzontal", "menu-more-vertical", "menu-right", "menu", "minus-circle", "minus-square", "minus", "mop", "office", "pharmacy-medical-pill", "pin-01", "pin-02", "pine-tree", "plant", "plus-circle", "plus-square", "plus", "power-plug-off", "power-plug", "projects-apps", "radio-empty", "remove-bookmark", "rocking-chair", "save", "search", "settings-01", "settings-02", "settings-03", "share-01", "share-02", "share-03", "share-04", "sign-in-log-in", "sign-out-log-out", "skull", "speedometer", "target-01", "target-02", "target-03", "tool", "toys-fan", "translate", "tree", "upload", "vaccine", "veg-non-veg", "virus", "wall"],
    bold: ["123", "3d-rotation", "abc", "accessibility", "accessible", "activity", "add-bookmark", "add-home", "anchor", "archive", "asterisk", "at-sign", "bone-pet-supplies", "bookmark-added", "bookmark", "bookmarks", "celebration", "check-tik-circle", "check-tik-square", "check-tik", "check-verified", "checkbox-checked", "checkbox-empty", "checkbox-indeterminate", "checklist", "chicken", "cleaning-services", "close-cancel-circle", "close-cancel-square", "close-cancel", "cloud-download", "cloud-upload", "coconut-tree", "cruelty-free-bunny", "dashboard", "delete", "dentistry", "divide", "doctor", "download", "eco-leaf", "egg", "electrical-services", "equal-not", "equal", "eye-closed", "eye-open", "fan-off", "fashion-clothes", "filter-01", "filter-02", "fish", "flower-01", "flower-02", "gesture", "grid-menu", "hash-01", "hash-02", "healing", "heart-activity", "heart-broken", "heart", "hearts", "hive", "home", "ladder", "lamp", "link-01", "link-02", "link-broken-01", "link-broken-02", "loading", "medical-square-hospital", "medical", "menu-left", "menu-more-horzontal", "menu-more-vertical", "menu-right", "menu", "minus-circle", "minus-square", "minus", "mop", "office", "pharmacy-medical-pill", "pin-01", "pin-02", "pine-tree", "plant", "plus-circle", "plus-square", "plus", "power-plug-off", "power-plug", "projects-apps", "radio-empty", "remove-bookmark", "rocking-chair", "save", "search", "settings-01", "settings-02", "settings-03", "share-01", "share-02", "share-03", "share-04", "sign-in-log-in", "sign-out-log-out", "skull", "speedometer", "target-01", "target-02", "target-03", "tool", "toys-fan", "translate", "tree", "upload", "vaccine", "veg-non-veg", "virus", "wall"],
    filled: ["123", "3d-rotation", "abc", "accessibility", "accessible", "activity", "add-bookmark", "add-home", "anchor", "archive", "asterisk", "at-sign", "bone-pet-supplies", "bookmark-added", "bookmark", "bookmarks", "celebration", "check-tik-circle", "check-tik-square", "check-tik", "check-verified", "checkbox-checked", "checkbox-empty", "checkbox-indeterminate", "checklist", "chicken", "cleaning-services", "close-cancel-circle", "close-cancel-square", "close-cancel", "cloud-download", "cloud-upload", "coconut-tree", "cruelty-free-bunny", "dashboard", "delete", "dentistry", "divide", "doctor", "download", "eco-leaf", "egg", "electrical-services", "equal-not", "equal", "eye-closed", "eye-open", "fan-off", "fashion-clothes", "filter-01", "filter-02", "fish", "flower-01", "flower-02", "gesture", "grid-menu", "hash-01", "hash-02", "healing", "heart-activity", "heart-broken", "heart", "hearts", "hive", "home", "ladder", "lamp", "link-01", "link-02", "link-broken-01", "link-broken-02", "loading", "medical-square-hospital", "medical", "menu-left", "menu-more-horzontal", "menu-more-vertical", "menu-right", "menu", "minus-circle", "minus-square", "minus", "mop", "office", "pharmacy-medical-pill", "pin-01", "pin-02", "pine-tree", "plant", "plus-circle", "plus-square", "plus", "power-plug-off", "power-plug", "projects-apps", "radio-empty", "remove-bookmark", "rocking-chair", "save", "search", "settings-01", "settings-02", "settings-03", "share-01", "share-02", "share-03", "share-04", "sign-in-log-in", "sign-out-log-out", "skull", "speedometer", "target-01", "target-02", "target-03", "tool", "toys-fan", "translate", "tree", "upload", "vaccine", "veg-non-veg", "virus", "wall"],
  },
  "layouts": {
    light: ["align-bottom-01", "align-bottom-02", "align-center-horizontal-01", "align-center-horizontal-02", "align-center-vertical-01", "align-center-vertical-02", "align-left-01", "align-left-02", "align-right-01", "align-right-02", "align-up-01", "align-up-02", "collapse-01", "collapse-02", "collapse-03", "collapse-04", "columns-01", "columns-02", "columns-03", "columns-04", "distribute-horizontal", "distribute-vertical", "divider", "expand-01", "expand-02", "expand-03", "expand-04", "expand-05", "expand-06", "fullscreen-exit", "fullscreen", "grid-dots-blank", "grid-dots-bottom", "grid-dots-horizontal-center", "grid-dots-left", "grid-dots-outer", "grid-dots-right", "grid-dots-top", "grid-dots-verticcal-center", "layer", "layers-01", "layers-02", "layout-grid-01", "layout-grid-02", "layout-grid-03", "layout-grid-04", "layout-left", "layout-right", "layout-top", "layout", "list", "responsive-layout", "rows-01", "rows-02", "rows-03", "rows-04", "split-down", "split-left", "split-right", "split-up", "table", "template"],
    medium: ["align-bottom-01", "align-bottom-02", "align-center-horizontal-01", "align-center-horizontal-02", "align-center-vertical-01", "align-center-vertical-02", "align-left-01", "align-left-02", "align-right-01", "align-right-02", "align-up-01", "align-up-02", "collapse-01", "collapse-02", "collapse-03", "collapse-04", "columns-01", "columns-02", "columns-03", "columns-04", "distribute-horizontal", "distribute-vertical", "divider", "expand-01", "expand-02", "expand-03", "expand-04", "expand-05", "expand-06", "fullscreen-exit", "fullscreen", "grid-dots-blank", "grid-dots-bottom", "grid-dots-horizontal-center", "grid-dots-left", "grid-dots-outer", "grid-dots-right", "grid-dots-top", "grid-dots-verticcal-center", "layer", "layers-01", "layers-02", "layout-grid-01", "layout-grid-02", "layout-grid-03", "layout-grid-04", "layout-left", "layout-right", "layout-top", "layout", "list", "responsive-layout", "rows-01", "rows-02", "rows-03", "rows-04", "split-down", "split-left", "split-right", "split-up", "table", "template"],
    bold: ["align-bottom-01", "align-bottom-02", "align-center-horizontal-01", "align-center-horizontal-02", "align-center-vertical-01", "align-center-vertical-02", "align-left-01", "align-left-02", "align-right-01", "align-right-02", "align-up-01", "align-up-02", "collapse-01", "collapse-02", "collapse-03", "collapse-04", "columns-01", "columns-02", "columns-03", "columns-04", "distribute-horizontal", "distribute-vertical", "divider", "expand-01", "expand-02", "expand-03", "expand-04", "expand-05", "expand-06", "fullscreen-exit", "fullscreen", "grid-dots-blank", "grid-dots-bottom", "grid-dots-horizontal-center", "grid-dots-left", "grid-dots-outer", "grid-dots-right", "grid-dots-top", "grid-dots-verticcal-center", "layer", "layers-01", "layers-02", "layout-grid-01", "layout-grid-02", "layout-grid-03", "layout-grid-04", "layout-left", "layout-right", "layout-top", "layout", "list", "responsive-layout", "rows-01", "rows-02", "rows-03", "rows-04", "split-down", "split-left", "split-right", "split-up", "table", "template"],
    filled: ["align-bottom-01", "align-bottom-02", "align-center-horizontal-01", "align-center-horizontal-02", "align-center-vertical-01", "align-center-vertical-02", "align-left-01", "align-left-02", "align-right-01", "align-right-02", "align-up-01", "align-up-02", "collapse-01", "collapse-02", "collapse-03", "collapse-04", "columns-01", "columns-02", "columns-03", "columns-04", "distribute-horizontal", "distribute-vertical", "divider", "expand-01", "expand-02", "expand-03", "expand-04", "expand-05", "expand-06", "fullscreen-exit", "fullscreen", "grid-dots-blank", "grid-dots-bottom", "grid-dots-horizontal-center", "grid-dots-left", "grid-dots-outer", "grid-dots-right", "grid-dots-top", "grid-dots-verticcal-center", "layer", "layers-01", "layers-02", "layout-grid-01", "layout-grid-02", "layout-grid-03", "layout-grid-04", "layout-left", "layout-right", "layout-top", "layout", "list", "responsive-layout", "rows-01", "rows-02", "rows-03", "rows-04", "split-down", "split-left", "split-right", "split-up", "table", "template"],
  },
  "maps-travel": {
    light: ["atm", "attraction", "bakery", "bar-01", "bar-02", "bar-03", "bar-04", "beach", "bed", "binoculars", "birthday-cake", "bus", "car", "casino", "castle", "chair-01", "chair-02", "checkroom-hanger", "chef", "church", "compass", "cottage", "escalator", "festival", "flag-01", "flag-02", "flight-ticket", "fort", "fuel-station", "gas-tank", "globe", "hotel", "ice-cream-01", "ice-cream-02", "local-activity", "local-cafe", "location-city", "luggage-01", "luggage-02", "lunch-dining", "map-01", "map-02", "mark", "mosque", "mountain", "museum", "navigation-pointer-01", "navigation-pointer-02", "night-life", "oil-barrel", "passport", "pin-01", "pin-02", "pin-03", "pin-04", "pin-05", "pizza", "plane-arrival", "plane-departure", "plane", "power-station", "recenter", "restaurant-01", "restaurant-02", "restaurant-table", "rocket", "room-service", "route", "school", "scooter", "ship", "shopping-local-mall", "spa", "stairs", "store-shop", "synagogue", "temple-buddhist", "temple-hindu", "tent", "ticket", "toilet-men", "toilet-wc", "toilet-women", "train", "tram", "truck"],
    medium: ["atm", "attraction", "bakery", "bar-01", "bar-02", "bar-03", "bar-04", "beach", "bed", "binoculars", "birthday-cake", "bus", "car", "casino", "castle", "chair-01", "chair-02", "checkroom-hanger", "chef", "church", "compass", "cottage", "escalator", "festival", "flag-01", "flag-02", "flight-ticket", "fort", "fuel-station", "gas-tank", "globe", "hotel", "ice-cream-01", "ice-cream-02", "local-activity", "local-cafe", "location-city", "luggage-01", "luggage-02", "lunch-dining", "map-01", "map-02", "mark", "mosque", "mountain", "museum", "navigation-pointer-01", "navigation-pointer-02", "night-life", "oil-barrel", "passport", "pin-01", "pin-02", "pin-03", "pin-04", "pin-05", "pizza", "plane-arrival", "plane-departure", "plane", "power-station", "recenter", "restaurant-01", "restaurant-02", "restaurant-table", "rocket", "room-service", "route", "school", "scooter", "ship", "shopping-local-mall", "spa", "stairs", "store-shop", "synagogue", "temple-buddhist", "temple-hindu", "tent", "ticket", "toilet-men", "toilet-wc", "toilet-women", "train", "tram", "truck"],
    bold: ["atm", "attraction", "bakery", "bar-01", "bar-02", "bar-03", "bar-04", "beach", "bed", "binoculars", "birthday-cake", "bus", "car", "casino", "castle", "chair-01", "chair-02", "checkroom-hanger", "chef", "church", "compass", "cottage", "escalator", "festival", "flag-01", "flag-02", "flight-ticket", "fort", "fuel-station", "gas-tank", "globe", "hotel", "ice-cream-01", "ice-cream-02", "local-activity", "local-cafe", "location-city", "luggage-01", "luggage-02", "lunch-dining", "map-01", "map-02", "mark", "mosque", "mountain", "museum", "navigation-pointer-01", "navigation-pointer-02", "night-life", "oil-barrel", "passport", "pin-01", "pin-02", "pin-03", "pin-04", "pin-05", "pizza", "plane-arrival", "plane-departure", "plane", "power-station", "recenter", "restaurant-01", "restaurant-02", "restaurant-table", "rocket", "room-service", "route", "school", "scooter", "ship", "shopping-local-mall", "spa", "stairs", "store-shop", "synagogue", "temple-buddhist", "temple-hindu", "tent", "ticket", "toilet-men", "toilet-wc", "toilet-women", "train", "tram", "truck"],
    filled: ["atm", "attraction", "bakery", "bar-01", "bar-02", "bar-03", "bar-04", "beach", "bed", "binoculars", "birthday-cake", "bus", "car", "casino", "castle", "chair-01", "chair-02", "checkroom-hanger", "chef", "church", "compass", "cottage", "escalator", "festival", "flag-01", "flag-02", "flight-ticket", "fort", "fuel-station", "gas-tank", "globe", "hotel", "ice-cream-01", "ice-cream-02", "local-activity", "local-cafe", "location-city", "luggage-01", "luggage-02", "lunch-dining", "map-01", "map-02", "mark", "mosque", "mountain", "museum", "navigation-pointer-01", "navigation-pointer-02", "night-life", "oil-barrel", "passport", "pin-01", "pin-02", "pin-03", "pin-04", "pin-05", "pizza", "plane-arrival", "plane-departure", "plane", "power-station", "recenter", "restaurant-01", "restaurant-02", "restaurant-table", "rocket", "room-service", "route", "school", "scooter", "ship", "shopping-local-mall", "spa", "stairs", "store-shop", "synagogue", "temple-buddhist", "temple-hindu", "tent", "ticket", "toilet-men", "toilet-wc", "toilet-women", "train", "tram", "truck"],
  },
  "media-devices": {
    light: ["airplay", "airpods", "battery-charging", "battery-empty", "battery-full", "battery-low", "battery-mid", "bluetooth-connect", "bluetooth-off", "bluetooth-on", "bluetooth-signal", "cable", "chromecast", "clapperboard", "disk", "fast-backward-circle", "fast-backward-square", "fast-backward", "fast-forward-circle", "fast-forward-square", "fast-forward", "film-cinema", "gamepad-01", "gamepad-02", "gaming-pad-01", "gaming-pad-02", "hard-drive", "headphones-mic", "headphones", "joystick", "keyboard", "laptop", "light-bulb-01", "light-bulb-02", "light-bulb-03", "light-bulb-04", "mic-mute", "mic", "mobile-phone-01", "mobile-phone-02", "modem", "monitor-01", "monitor-02", "monitor-03", "mouse", "music-note-01", "music-note-02", "panorama-horizontal", "panorama-vertical", "pause-circle", "pause-square", "pause", "photograph", "play-circle", "play-square", "play", "podcast", "power-circle", "power", "printer", "recording", "rss-01", "rss-02", "signal-01", "signal-02", "simcard", "skip-backward-circle", "skip-backward-square", "skip-backward", "skip-forward-circle", "skip-forward-square", "skip-forward", "sliders-01", "sliders-02", "speaker", "stop-circle", "stop-square", "stop", "tv", "usb", "video-off", "video", "voicemail", "volume-max", "volume-min", "volume-minus", "volume-plus", "volume-x", "webcam", "wifi-off", "wifi"],
    medium: ["airplay", "airpods", "battery-charging", "battery-empty", "battery-full", "battery-low", "battery-mid", "bluetooth-connect", "bluetooth-off", "bluetooth-on", "bluetooth-signal", "cable", "chromecast", "clapperboard", "disk", "fast-backward-circle", "fast-backward-square", "fast-backward", "fast-forward-circle", "fast-forward-square", "fast-forward", "film-cinema", "gamepad-01", "gamepad-02", "gaming-pad-01", "gaming-pad-02", "hard-drive", "headphones-mic", "headphones", "joystick", "keyboard", "laptop", "light-bulb-01", "light-bulb-02", "light-bulb-03", "light-bulb-04", "mic-mute", "mic", "mobile-phone-01", "mobile-phone-02", "modem", "monitor-01", "monitor-02", "monitor-03", "mouse", "music-note-01", "music-note-02", "panorama-horizontal", "panorama-vertical", "pause-circle", "pause-square", "pause", "photograph", "play-circle", "play-square", "play", "podcast", "power-circle", "power", "printer", "recording", "rss-01", "rss-02", "signal-01", "signal-02", "simcard", "skip-backward-circle", "skip-backward-square", "skip-backward", "skip-forward-circle", "skip-forward-square", "skip-forward", "sliders-01", "sliders-02", "speaker", "stop-circle", "stop-square", "stop", "tv", "usb", "video-off", "video", "voicemail", "volume-max", "volume-min", "volume-minus", "volume-plus", "volume-x", "webcam", "wifi-off", "wifi"],
    bold: ["airplay", "airpods", "battery-charging", "battery-empty", "battery-full", "battery-low", "battery-mid", "bluetooth-connect", "bluetooth-off", "bluetooth-on", "bluetooth-signal", "cable", "chromecast", "clapperboard", "disk", "fast-backward-circle", "fast-backward-square", "fast-backward", "fast-forward-circle", "fast-forward-square", "fast-forward", "film-cinema", "gamepad-01", "gamepad-02", "gaming-pad-01", "gaming-pad-02", "hard-drive", "headphones-mic", "headphones", "joystick", "keyboard", "laptop", "light-bulb-01", "light-bulb-02", "light-bulb-03", "light-bulb-04", "mic-mute", "mic", "mobile-phone-01", "mobile-phone-02", "modem", "monitor-01", "monitor-02", "monitor-03", "mouse", "music-note-01", "music-note-02", "panorama-horizontal", "panorama-vertical", "pause-circle", "pause-square", "pause", "photograph", "play-circle", "play-square", "play", "podcast", "power-circle", "power", "printer", "recording", "rss-01", "rss-02", "signal-01", "signal-02", "simcard", "skip-backward-circle", "skip-backward-square", "skip-backward", "skip-forward-circle", "skip-forward-square", "skip-forward", "sliders-01", "sliders-02", "speaker", "stop-circle", "stop-square", "stop", "tv", "usb", "video-off", "video", "voicemail", "volume-max", "volume-min", "volume-minus", "volume-plus", "volume-x", "webcam", "wifi-off", "wifi"],
    filled: ["airplay", "airpods", "battery-charging", "battery-empty", "battery-full", "battery-low", "battery-mid", "bluetooth-connect", "bluetooth-off", "bluetooth-on", "bluetooth-signal", "cable", "chromecast", "clapperboard", "disk", "fast-backward-circle", "fast-backward-square", "fast-backward", "fast-forward-circle", "fast-forward-square", "fast-forward", "film-cinema", "gamepad-01", "gamepad-02", "gaming-pad-01", "gaming-pad-02", "hard-drive", "headphones-mic", "headphones", "joystick", "keyboard", "laptop", "light-bulb-01", "light-bulb-02", "light-bulb-03", "light-bulb-04", "mic-mute", "mic", "mobile-phone-01", "mobile-phone-02", "modem", "monitor-01", "monitor-02", "monitor-03", "mouse", "music-note-01", "music-note-02", "panorama-horizontal", "panorama-vertical", "pause-circle", "pause-square", "pause", "photograph", "play-circle", "play-square", "play", "podcast", "power-circle", "power", "printer", "recording", "rss-01", "rss-02", "signal-01", "signal-02", "simcard", "skip-backward-circle", "skip-backward-square", "skip-backward", "skip-forward-circle", "skip-forward-square", "skip-forward", "sliders-01", "sliders-02", "speaker", "stop-circle", "stop-square", "stop", "tv", "usb", "video-off", "video", "voicemail", "volume-max", "volume-min", "volume-minus", "volume-plus", "volume-x", "webcam", "wifi-off", "wifi"],
  },
  "security": {
    light: ["crime", "face-id-circle", "face-id-square", "face-id", "finger-print-off", "finger-print", "helmet", "key-hole-circle", "key-hole-square", "key", "lock", "passcode-lock", "passcode", "scan", "shield-check", "shield-off", "shield-plus", "shield", "unlock"],
    medium: ["crime", "face-id-circle", "face-id-square", "face-id", "finger-print-off", "finger-print", "helmet", "key-hole-circle", "key-hole-square", "key", "lock", "passcode-lock", "passcode", "scan", "shield-check", "shield-off", "shield-plus", "shield", "unlock"],
    bold: ["crime", "face-id-circle", "face-id-square", "face-id", "finger-print-off", "finger-print", "helmet", "key-hole-circle", "key-hole-square", "key", "lock", "passcode-lock", "passcode", "scan", "shield-check", "shield-off", "shield-plus", "shield", "unlock"],
    filled: ["crime", "face-id-circle", "face-id-square", "face-id", "finger-print-off", "finger-print", "helmet", "key-hole-circle", "key-hole-square", "key", "lock", "passcode-lock", "passcode", "scan", "shield-check", "shield-off", "shield-plus", "shield", "unlock"],
  },
  "shapes": {
    light: ["circle", "club", "cube-01", "cube-02", "cube-03", "cube-04", "cube-outline", "diamond", "dot-01", "dot-02", "hexagon-01", "hexagon-02", "line", "octagon-01", "octagon-02", "pentagon", "spade", "square-rounded", "square", "star-01", "star-02", "star-03", "star-04", "star-05", "stars", "triangle"],
    medium: ["circle", "club", "cube-01", "cube-02", "cube-03", "cube-04", "cube-outline", "diamond", "dot-01", "dot-02", "hexagon-01", "hexagon-02", "line", "octagon-01", "octagon-02", "pentagon", "spade", "square-rounded", "square", "star-01", "star-02", "star-03", "star-04", "star-05", "stars", "triangle"],
    bold: ["circle", "club", "cube-01", "cube-02", "cube-03", "cube-04", "cube-outline", "diamond", "dot-01", "dot-02", "hexagon-01", "hexagon-02", "line", "octagon-01", "octagon-02", "pentagon", "spade", "square-rounded", "square", "star-01", "star-02", "star-03", "star-04", "star-05", "stars", "triangle"],
    filled: ["circle", "club", "cube-01", "cube-02", "cube-03", "cube-04", "cube-outline", "diamond", "dot-01", "dot-02", "hexagon-01", "hexagon-02", "line", "octagon-01", "octagon-02", "pentagon", "spade", "square-rounded", "square", "star-01", "star-02", "star-03", "star-04", "star-05", "stars", "triangle"],
  },
  "sports": {
    light: ["badminton-01", "badminton-02", "baseball", "basketball", "bicycle", "bike", "bottle", "boxing", "checkered-flag", "chess-bishop", "chess-king", "chess-knight", "chess-pawn", "chess-queen", "chess-rook", "chess", "club", "cricket", "cycling", "football", "golf-course", "golf", "gym", "hiking", "hockey", "ice-skating", "net-01", "net-02", "padel", "pickleball", "playing-cards", "roller-skating", "rugby", "run-sprint", "sailing", "shoe", "spade", "sports", "stadium", "steps", "swimming-pool", "table-tennis", "tennis", "walk", "weight", "yoga"],
    medium: ["badminton-01", "badminton-02", "baseball", "basketball", "bicycle", "bike", "bottle", "boxing", "checkered-flag", "chess-bishop", "chess-king", "chess-knight", "chess-pawn", "chess-queen", "chess-rook", "chess", "club", "cricket", "cycling", "football", "golf-course", "golf", "gym", "hiking", "hockey", "ice-skating", "net-01", "net-02", "padel", "pickleball", "playing-cards", "roller-skating", "rugby", "run-sprint", "sailing", "shoe", "spade", "sports", "stadium", "steps", "swimming-pool", "table-tennis", "tennis", "walk", "weight", "yoga"],
    bold: ["badminton-01", "badminton-02", "baseball", "basketball", "bicycle", "bike", "bottle", "boxing", "checkered-flag", "chess-bishop", "chess-king", "chess-knight", "chess-pawn", "chess-queen", "chess-rook", "chess", "club", "cricket", "cycling", "football", "golf-course", "golf", "gym", "hiking", "hockey", "ice-skating", "net-01", "net-02", "padel", "pickleball", "playing-cards", "roller-skating", "rugby", "run-sprint", "sailing", "shoe", "spade", "sports", "stadium", "steps", "swimming-pool", "table-tennis", "tennis", "walk", "weight", "yoga"],
    filled: ["badminton-01", "badminton-02", "baseball", "basketball", "bicycle", "bike", "bottle", "boxing", "checkered-flag", "chess-bishop", "chess-king", "chess-knight", "chess-pawn", "chess-queen", "chess-rook", "chess", "club", "cricket", "cycling", "football", "golf-course", "golf", "gym", "hiking", "hockey", "ice-skating", "net-01", "net-02", "padel", "pickleball", "playing-cards", "roller-skating", "rugby", "run-sprint", "sailing", "shoe", "spade", "sports", "stadium", "steps", "swimming-pool", "table-tennis", "tennis", "walk", "weight", "yoga"],
  },
  "time": {
    light: ["add-alarm", "alarm-set", "alarm", "calendar-check", "calendar-minus", "calendar-plus", "calendar-today", "calendar-x", "calendar", "clock-check", "clock-minus", "clock-plus", "clock-refresh", "clock-x", "clock", "hourglass", "remove-alarm", "stopwatch", "timeline", "watch"],
    medium: ["add-alarm", "alarm-set", "alarm", "calendar-check", "calendar-minus", "calendar-plus", "calendar-today", "calendar-x", "calendar", "clock-check", "clock-minus", "clock-plus", "clock-refresh", "clock-x", "clock", "hourglass", "remove-alarm", "stopwatch", "timeline", "watch"],
    bold: ["add-alarm", "alarm-set", "alarm", "calendar-check", "calendar-minus", "calendar-plus", "calendar-today", "calendar-x", "calendar", "clock-check", "clock-minus", "clock-plus", "clock-refresh", "clock-x", "clock", "hourglass", "remove-alarm", "stopwatch", "timeline", "watch"],
    filled: ["add-alarm", "alarm-set", "alarm", "calendar-check", "calendar-minus", "calendar-plus", "calendar-today", "calendar-x", "calendar", "clock-check", "clock-minus", "clock-plus", "clock-refresh", "clock-x", "clock", "hourglass", "remove-alarm", "stopwatch", "timeline", "watch"],
  },
  "users": {
    light: ["add-user", "edit-user", "face-happy-01", "face-happy-02", "face-sad", "face-wink", "people", "remove-user", "teams", "user-account-manage", "user-check", "user-circle", "user-square", "user-x", "user", "users"],
    medium: ["add-user", "edit-user", "face-happy-01", "face-happy-02", "face-sad", "face-wink", "people", "remove-user", "teams", "user-account-manage", "user-check", "user-circle", "user-square", "user-x", "user", "users"],
    bold: ["add-user", "edit-user", "face-happy-01", "face-happy-02", "face-sad", "face-wink", "people", "remove-user", "teams", "user-account-manage", "user-check", "user-circle", "user-square", "user-x", "user", "users"],
    filled: ["add-user", "edit-user", "face-happy-01", "face-happy-02", "face-sad", "face-wink", "people", "remove-user", "teams", "user-account-manage", "user-check", "user-circle", "user-square", "user-x", "user", "users"],
  },
  "weather": {
    light: ["cloud-lightning", "cloud-moon", "cloud-raining-01", "cloud-raining-02", "cloud-raining-03", "cloud-raining-04", "cloud-raining-05", "cloud-raining-06", "cloud-raining-lightning", "cloud-snowing-01", "cloud-snowing-02", "cloud-sun", "cloud", "clouds", "droplets-01", "droplets-02", "fog-01", "fog-02", "hurricane", "lightning", "mist", "moon-star-clear-night", "moon", "rain", "snowflake", "snowing-heavily", "snowing", "stars-01", "stars-02", "stars-03", "sun", "sunrise", "sunset", "thermometer-cold", "thermometer-hot", "thermometer", "umbrella", "waves", "wind-01", "wind-02"],
    medium: ["cloud-lightning", "cloud-moon", "cloud-raining-01", "cloud-raining-02", "cloud-raining-03", "cloud-raining-04", "cloud-raining-05", "cloud-raining-06", "cloud-raining-lightning", "cloud-snowing-01", "cloud-snowing-02", "cloud-sun", "cloud", "clouds", "droplets-01", "droplets-02", "fog-01", "fog-02", "hurricane", "lightning", "mist", "moon-star-clear-night", "moon", "rain", "snowflake", "snowing-heavily", "snowing", "stars-01", "stars-02", "stars-03", "sun", "sunrise", "sunset", "thermometer-cold", "thermometer-hot", "thermometer", "umbrella", "waves", "wind-01", "wind-02"],
    bold: ["cloud-lightning", "cloud-moon", "cloud-raining-01", "cloud-raining-02", "cloud-raining-03", "cloud-raining-04", "cloud-raining-05", "cloud-raining-06", "cloud-raining-lightning", "cloud-snowing-01", "cloud-snowing-02", "cloud-sun", "cloud", "clouds", "droplets-01", "droplets-02", "fog-01", "fog-02", "hurricane", "lightning", "mist", "moon-star-clear-night", "moon", "rain", "snowflake", "snowing-heavily", "snowing", "stars-01", "stars-02", "stars-03", "sun", "sunrise", "sunset", "thermometer-cold", "thermometer-hot", "thermometer", "umbrella", "waves", "wind-01", "wind-02"],
    filled: ["cloud-lightning", "cloud-moon", "cloud-raining-01", "cloud-raining-02", "cloud-raining-03", "cloud-raining-04", "cloud-raining-05", "cloud-raining-06", "cloud-raining-lightning", "cloud-snowing-01", "cloud-snowing-02", "cloud-sun", "cloud", "clouds", "droplets-01", "droplets-02", "fog-01", "fog-02", "hurricane", "lightning", "mist", "moon-star-clear-night", "moon", "rain", "snowflake", "snowing-heavily", "snowing", "stars-01", "stars-02", "stars-03", "sun", "sunrise", "sunset", "thermometer-cold", "thermometer-hot", "thermometer", "umbrella", "waves", "wind-01", "wind-02"],
  },
};

function iconLabel(slug) {
  return slug.replace(/-/g, " ");
}

function getAllIcons() {
  const out = [];
  for (const category of CATEGORIES) {
    const byWeight = ICONS[category.slug] || {};
    const anyWeightSlugs = new Set();
    for (const w of WEIGHTS) (byWeight[w] || []).forEach((s) => anyWeightSlugs.add(s));
    for (const slug of anyWeightSlugs) {
      out.push({
        slug,
        name: iconLabel(slug),
        category: category.slug,
        categoryName: category.name,
        weights: WEIGHTS.filter((w) => (byWeight[w] || []).includes(slug)),
      });
    }
  }
  return out;
}

function iconSvgPath(categorySlug, weight, iconSlug) {
  return `icons/${categorySlug}/${weight}/${iconSlug}.svg`;
}
